#!/bin/bash
sudo apt-get install --no-install-recommends devscripts build-essential fakeroot debhelper gnupg dh-make lintian ubuntu-dev-tools cdbs devscripts build-essential fakeroot debhelper gnupg dh-make lintian ubuntu-dev-tools cdbs dpkg-sig reprepro figlet 
sudo dpkg --configure -a
#NON Aktifkan repository os sejenak
#bugs karena di repo utama diprioritaskan utma sedangkan paketnya dibawah
sudo apt-cache policy libc6 libc6-dev locales
